Update trans7.yml

diff --git a/.github/workflows/trans7.yml b/.github/workflows/trans7.yml
--- a/.github/workflows/trans7.yml
+++ b/.github/workflows/trans7.yml
@@ -24,14 +24,16 @@ jobs:
         run: |
           python3 scriptdaily.py "" https://www.dailymotion.com/video/x8qckyq
 
-      - name: Commit m3u8 file
+       - name: Commit m3u8 file
         shell: bash
         run: |
           git config --global user.name "github-actions[bot]"
           git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
+          
           if [ -f "trans7.m3u8" ]; then
             git add trans7.m3u8
-            git commit -m "Update trans7.m3u8 [auto]" || echo "No changes"
+            git commit -m "Update trans7.m3u8 [auto]" || echo "No changes to commit"
             git push
           else
-            echo "File trans7.m3u8 not found"
+            echo "File trans7.m3u8 not found, skipping commit."
+          fi
