Update trans7.yml

diff --git a/.github/workflows/trans7.yml b/.github/workflows/trans7.yml
--- a/.github/workflows/trans7.yml
+++ b/.github/workflows/trans7.yml
@@ -22,11 +22,12 @@ jobs:
         run: pip install requests
 
       - name: Run proxy checker
-        run: python3 proxy_checker.py
+        run: python3 proxy_checker.py || echo "proxy_checker error diabaikan"
 
       - name: Run Dailymotion HLS fetcher
         run: |
           PROXY=$(cat valid_proxy.txt || echo "")
+          echo "Using proxy: $PROXY"
           python3 scriptdaily.py "$PROXY" "https://www.dailymotion.com/video/x8qckyq" "trans7.m3u8"
 
       - name: Commit and Push result
